### ISSUE TITLE
안드로이드 앱 취약점 진단 환경 소개와 설치 수강

### ISSUE THREAD

**Issue by Joseph-Cha** [Joseph-Cha/AndroidSecureCodingLectureNote#1]
### To-Do
- [ ] 인시큐어 뱅크 환경 구축 - 아나콘다 환경 구축
- [ ] 앱 취약점 분석을 위한 도구 리뷰
- [ ] 정적 분석 환경 구성
- [ ] 동적 분석 환경 구성
